#!/bin/bash

list_devices() {
    # Add a bunch of (optional) devices
    # (Don't add them unconditionally: if they don't exist, it
    # would prevent the container from starting)
    #DEVICES=
    echo "    devices:"
    for DEV in /dev/kvm /dev/ttyUSB\* /dev/dri/* /dev/snd/*; do
        if [ -b "$DEV" -o -c "$DEV" ]; then
            #DEVICES="$DEVICES    - $DEV:$DEV \n"
            echo "        - $DEV:$DEV"
        fi
    done
    #echo "$DEVICES"
}

list_volumes() {
    # And a few (optional) files
    # Here again, they don't always exist everywhere
    echo "    volumes:"
    for VOL in /tmp/.X11-unix /run/user; do
        if [ -e "$VOL" ]; then
            #VOLUMES="$VOLUMES --volume $VOL:$VOL"
            echo "        - $VOL:$VOL"
        fi
    done
}

list_envvars() {
    ENVVARS="
        SSH_AGENT_PID
        SSH_AUTH_SOCK
        SSH_AUTH_DIRNAME
        DISPLAY
        TERM
        TERMINAL
        ROXTERM_ID
        ROXTERM_NUM
        ROXTERM_PID
        QT_DEVICE_PIXEL_RATIO
        GDK_DPI_SCALE
        GDK_SCALE
        DBUS_SESSION_BUS_ADDRESS
        FOO
        "

    echo "    environment:"
    for envvar in $ENVVARS; do
        #echo "export $envvar='${!envvar}'"
        if [ ! -z ${!envvar} ]; then
            echo "        - $envvar=\${$envvar}"
        fi
    done

    #for VAR in "$ENVVARS"; do
    #    echo "export $VAR='${!VAR}'"
    #done

}

install_java() {
    msg="
# Install Java.
RUN apt-get update && \\
    apt-get upgrade -y && \\
    apt-get install -y  software-properties-common && \\
    add-apt-repository ppa:webupd8team/java -y && \\
    apt-get update && \\
    echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \\
    apt-get install -y oracle-java8-installer && \\
    apt-get clean

ENV MAVEN_VERSION 3.3.9

RUN curl -fsSL https://archive.apache.org/dist/maven/maven-3/\$MAVEN_VERSION/binaries/apache-maven-\$MAVEN_VERSION-bin.tar.gz \\
    | tar xzf - -C /usr/share \\
  && mv /usr/share/apache-maven-\$MAVEN_VERSION /usr/share/maven \\
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

# Define working directory.
WORKDIR /data

# Define commonly used JAVA_HOME variable
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle"
    echo "$msg"
}

list_devices
list_volumes
list_envvars

if [ ! $SHELL="usr/bin/zsh" ]; then
    list_envvars
    # install_java
fi
